// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/password/v1/code_delivery_options.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CodeDeliveryOptions struct {
	PhoneNumbers         []*PhoneNumberOption  `protobuf:"bytes,1,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	EmailAddresses       []*EmailAddressOption `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CodeDeliveryOptions) Reset()         { *m = CodeDeliveryOptions{} }
func (m *CodeDeliveryOptions) String() string { return proto.CompactTextString(m) }
func (*CodeDeliveryOptions) ProtoMessage()    {}
func (*CodeDeliveryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f78f8db2dc5fc7, []int{0}
}

func (m *CodeDeliveryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeDeliveryOptions.Unmarshal(m, b)
}
func (m *CodeDeliveryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeDeliveryOptions.Marshal(b, m, deterministic)
}
func (m *CodeDeliveryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeDeliveryOptions.Merge(m, src)
}
func (m *CodeDeliveryOptions) XXX_Size() int {
	return xxx_messageInfo_CodeDeliveryOptions.Size(m)
}
func (m *CodeDeliveryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeDeliveryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CodeDeliveryOptions proto.InternalMessageInfo

func (m *CodeDeliveryOptions) GetPhoneNumbers() []*PhoneNumberOption {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *CodeDeliveryOptions) GetEmailAddresses() []*EmailAddressOption {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

type PhoneNumberOption struct {
	// primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// associated account
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// actual value
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumberOption) Reset()         { *m = PhoneNumberOption{} }
func (m *PhoneNumberOption) String() string { return proto.CompactTextString(m) }
func (*PhoneNumberOption) ProtoMessage()    {}
func (*PhoneNumberOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f78f8db2dc5fc7, []int{1}
}

func (m *PhoneNumberOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumberOption.Unmarshal(m, b)
}
func (m *PhoneNumberOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumberOption.Marshal(b, m, deterministic)
}
func (m *PhoneNumberOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumberOption.Merge(m, src)
}
func (m *PhoneNumberOption) XXX_Size() int {
	return xxx_messageInfo_PhoneNumberOption.Size(m)
}
func (m *PhoneNumberOption) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumberOption.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumberOption proto.InternalMessageInfo

func (m *PhoneNumberOption) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PhoneNumberOption) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *PhoneNumberOption) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type EmailAddressOption struct {
	// primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// associated account
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// actual value
	EmailAddress         string   `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAddressOption) Reset()         { *m = EmailAddressOption{} }
func (m *EmailAddressOption) String() string { return proto.CompactTextString(m) }
func (*EmailAddressOption) ProtoMessage()    {}
func (*EmailAddressOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f78f8db2dc5fc7, []int{2}
}

func (m *EmailAddressOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAddressOption.Unmarshal(m, b)
}
func (m *EmailAddressOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAddressOption.Marshal(b, m, deterministic)
}
func (m *EmailAddressOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAddressOption.Merge(m, src)
}
func (m *EmailAddressOption) XXX_Size() int {
	return xxx_messageInfo_EmailAddressOption.Size(m)
}
func (m *EmailAddressOption) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAddressOption.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAddressOption proto.InternalMessageInfo

func (m *EmailAddressOption) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailAddressOption) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *EmailAddressOption) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*CodeDeliveryOptions)(nil), "alpacalabs.password.v1.CodeDeliveryOptions")
	proto.RegisterType((*PhoneNumberOption)(nil), "alpacalabs.password.v1.PhoneNumberOption")
	proto.RegisterType((*EmailAddressOption)(nil), "alpacalabs.password.v1.EmailAddressOption")
}

func init() {
	proto.RegisterFile("alpacalabs/password/v1/code_delivery_options.proto", fileDescriptor_e4f78f8db2dc5fc7)
}

var fileDescriptor_e4f78f8db2dc5fc7 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0x29, 0x08, 0xdd, 0xfe, 0x88, 0x11, 0x4a, 0x10, 0x84, 0x5a, 0x2f, 0x55, 0xe8, 0x86,
	0xd4, 0x27, 0x68, 0xd5, 0x83, 0x50, 0x6a, 0xa8, 0xd0, 0x83, 0x14, 0xc2, 0x26, 0x3b, 0xb4, 0x0b,
	0x49, 0x66, 0xc9, 0xa6, 0x15, 0x5f, 0xc7, 0x9b, 0x3e, 0x82, 0x8f, 0xe0, 0x53, 0x49, 0xb6, 0x09,
	0x8d, 0xb4, 0x3d, 0x78, 0xdc, 0x6f, 0xbe, 0x9f, 0x99, 0xd9, 0x21, 0x43, 0x16, 0x49, 0x16, 0xb2,
	0x88, 0x05, 0xca, 0x91, 0x4c, 0xa9, 0x37, 0x4c, 0xb9, 0xb3, 0x71, 0x9d, 0x10, 0x39, 0xf8, 0x1c,
	0x22, 0xb1, 0x81, 0xf4, 0xdd, 0x47, 0x99, 0x09, 0x4c, 0x14, 0x95, 0x29, 0x66, 0x68, 0x75, 0x76,
	0x1a, 0x5a, 0x6a, 0xe8, 0xc6, 0xed, 0x7d, 0x1b, 0xe4, 0xfc, 0x1e, 0x39, 0x3c, 0x14, 0xb2, 0xe7,
	0xad, 0xca, 0x9a, 0x92, 0x96, 0x5c, 0x61, 0x02, 0x7e, 0xb2, 0x8e, 0x03, 0x48, 0x95, 0x6d, 0x74,
	0x6b, 0xfd, 0xc6, 0xf0, 0x86, 0x1e, 0xf6, 0xa1, 0x5e, 0x4e, 0x9e, 0x6a, 0xee, 0xd6, 0x62, 0xd6,
	0x94, 0x3b, 0x48, 0x59, 0x2f, 0xe4, 0x14, 0x62, 0x26, 0x22, 0x9f, 0x71, 0x9e, 0x82, 0x52, 0xa0,
	0x6c, 0x53, 0x3b, 0xde, 0x1e, 0x73, 0x7c, 0xcc, 0xe9, 0xa3, 0x2d, 0xbb, 0xb0, 0x6c, 0x43, 0x05,
	0x03, 0xd5, 0x03, 0x72, 0xb6, 0x97, 0x6b, 0xb5, 0x89, 0x29, 0xb8, 0x6d, 0x74, 0x8d, 0x7e, 0x7d,
	0x66, 0x0a, 0x6e, 0x5d, 0x12, 0xc2, 0xc2, 0x10, 0xd7, 0x49, 0xe6, 0x0b, 0x6e, 0x9b, 0x1a, 0xaf,
	0x17, 0xc8, 0x13, 0xb7, 0xae, 0x48, 0xb3, 0x3a, 0xa8, 0x5d, 0xd3, 0x84, 0x46, 0xa5, 0xf9, 0xde,
	0x8a, 0x58, 0xfb, 0xcd, 0xfc, 0x37, 0xe7, 0x9a, 0xb4, 0xfe, 0x2c, 0xa0, 0x08, 0x6a, 0x56, 0x47,
	0x1a, 0x7f, 0x1a, 0xe4, 0x22, 0xc4, 0xf8, 0xc8, 0x4a, 0xc6, 0x2d, 0xaf, 0x78, 0x78, 0xf9, 0x9f,
	0x7a, 0xc6, 0xeb, 0x78, 0x29, 0xb2, 0xd5, 0x3a, 0xa0, 0x21, 0xc6, 0xce, 0x48, 0x6b, 0x26, 0xfa,
	0x28, 0xf2, 0x72, 0x0a, 0x12, 0x07, 0xa5, 0x7a, 0xb0, 0x44, 0xe7, 0xf0, 0xd5, 0x7c, 0x98, 0xb5,
	0xd1, 0xc4, 0xfb, 0x32, 0x3b, 0x3b, 0x3d, 0x2d, 0x63, 0xe8, 0xdc, 0xfd, 0xa9, 0x16, 0x16, 0x65,
	0x61, 0x31, 0x77, 0x83, 0x13, 0x9d, 0x72, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x4f, 0x02,
	0x0a, 0x8e, 0x02, 0x00, 0x00,
}
